language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: nicklas2751-github
before_install:
  - chmod +x mvnw  
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/secring.gpg.enc -out .travis/secring.gpg -d
  - gpg --fast-import .travis/secring.gpg    
stages:
- Test
- name: Deploy
  if: branch IN (master,development) OR tag = true
jobs:
  include:
  - stage: Test
    script:
    - ./mvnw clean verify sonar:sonar
    cache:
      directories:
      - .autoconf
      - $HOME/.m2
  - stage: Deploy
    script:
    - ./mvnw clean install
    cache:
      directories:
      - .autoconf
      - $HOME/.m2    
    deploy:
      - provider: script
        script:
          - ./mvnw --settings .maven.xml deploy
        skip_cleanup: true
        on:
            all_branches: true
      - provider: releases
        api_key:
          secure: $GITHUB_DEPLOY_TOKEN
        file_glob: true
        file:
        - target/*
        skip_cleanup: true
        on:
          tags: true