language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: nicklas2751-github
    branches:
    - master
    - develop
    - feature/.*
    - hotfix/.*
stages:
- Test
- name: Deploy
  if: branch = master OR tag = true
jobs:
  include:
  - stage: Test
    script:
    - chmod +x mvnw
    - ./mvnw clean verify
    cache:
      directories:
      - .autoconf
      - $HOME/.m2
    after_success:
    - sonar-scanner
  - stage: Deploy
    script:
    - chmod +x mvnw
    - ./mvnw clean install
    cache:
      directories:
      - .autoconf
      - $HOME/.m2
    before_deploy:
    - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/secring.gpg.enc
      -out .travis/secring.gpg -d
    deploy:
      - provider: script
        script:
          - chmod +x mvnw
          - ./mvnw --settings .maven.xml deploy
        skip_cleanup: true
      - provider: releases
        api_key:
          secure: $GITHUB_DEPLOY_TOKEN
        file_glob: true
        file:
        - target/*
        skip_cleanup: true
        on:
          tags: true
